Feat: Create a Basic Prototype App
PasscodesApp/Passcodes pull request #5
Opened 2024-08-11 15:55 UTC by JeelDobariya38

# Change Made
- create a basic functional app.
- refactor the existing permission code.
- extended the ui.

> [!Important]
> due to less info about the android ecosystem. I can't implement the list scrollable view of password for load password activity.

2024-08-11 16:58 UTC, kudanilll requested changes
- For Activity files, store them in the `packages/ui/here` folder so that the folder is more structured.
- I recommend using `ViewBinding` so that the code looks cleaner and easier to maintain and you don't need to create an init variable function.
- For the toast message don't write it directly in hard code, use `getString` and `strings.xml`.

2024-08-12 06:20 UTC, JeelDobariya38 commented
> * For Activity files, store them in the `packages/ui/here` folder so that the folder is more structured.
> * I recommend using `ViewBinding` so that the code looks cleaner and easier to maintain and you don't need to create an init variable function.
> * For the toast message don't write it directly in hard code, use `getString` and `strings.xml`.

Implement all of this. 
Is there anything else, yet left. Other then, the permission issue in lower Android version?

2024-08-12 14:57 UTC, JeelDobariya38 commented
implemented all the changes which we requested and also **add the listview using chatgpt**. @kudanilll

2024-08-13 05:38 UTC, HamadaNative approved these changes

2024-08-13 12:43 UTC, kudanilll approved these changes

2024-08-13 12:44 UTC, merged